name: arditya.architect
favicon: null
layout_spectrum: 0.07635
typography_spectrum: 0.5868714845273644
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.25172716774977744
  lightness: 0.7495697881095111
  saturation: 0.5908901158254594
  rhythmicContrast: 0.7969204434193671
purpose: []
